### ISSUE TITLE
Request for Implementation Details

### ISSUE THREAD

**Issue by Forest-Lee** [zhang-guangyi/t-udeepsc#3]
Hi, I'm interested in your  work presented in the paper `A Unified Multi-Task Semantic Communication System for Multimodal Data`, and I found the concepts and results quite inspiring. Thus, I would like to **replicate your study** for further understanding. 

However, when I tried to run the `execute.sh` following your instructions in `README.md`, I was stuck at the code in `model.py`.
```
bert_ckpt = f"/Data1/zhangguangyi/SemanRes2/JSACCode/UDeepSC_Base/pretrained_models/bert-{mode}"
self.text_encoder = BertModel.from_pretrained(bert_ckpt)
```

If it is convenient, could you please provide more details for the `pretrained_model` and `requirements.txt`?

Thanks for your excellent work. Best wishes!

**Comment by Forest-Lee** [comment]
Just download the pretrained models mannually, never mind.

**Comment by aegisoverload** [comment]
Hello, I have some questions about this project.
May I have some of your time?

**Comment by Forest-Lee** [comment]
> Hello, I have some questions about this project. May I have some of your time?

Absolutely, feel free to contact me via lipeijiegg@gmail.com.
